version: "3.9"

services:
 db:
   image: postgres:alpine
   restart: unless-stopped
   environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"
 nginx:
   image: nginx
   restart: unless-stopped
 app:
   build: .